#!/bin/sh

set -e
DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
cd $DIR

if [ ! -d libs ];
then
    mkdir libs
fi

if [ ! -f libs/square-otto-1.3.2.jar ];
then
    if [ ! -d ~/.soomla ];
    then
        mkdir ~/.soomla
    fi
    if [ ! -d ~/.soomla/cache ];
    then
        mkdir ~/.soomla/cache
    fi
    if [ ! -d ~/.soomla/cache/android-core ];
    then
        mkdir ~/.soomla/cache/android-core
    fi

    if [ ! -f ~/.soomla/cache/android-core/square-otto-1.3.2.jar ];
    then
        curl -o ~/.soomla/cache/android-core/square-otto-1.3.2.jar https://cloud.github.com/downloads/square/otto/square-otto-1.3.2.jar
    fi
    cp ~/.soomla/cache/android-core/square-otto-1.3.2.jar libs/square-otto-1.3.2.jar
fi